# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfilm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('director', models.TextField(blank=True, null=True)),
                ('edit', models.TextField(blank=True, null=True)),
                ('star', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('region', models.TextField(blank=True, null=True)),
                ('language', models.TextField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('length', models.TextField(blank=True, null=True)),
                ('othername', models.TextField(blank=True, null=True)),
                ('imdblink', models.TextField(blank=True, db_column='IMDblink', null=True)),
                ('brief', models.TextField(blank=True, null=True)),
                ('douban', models.TextField(blank=True, null=True)),
                ('postlink', models.TextField(blank=True, null=True)),
                ('imdb', models.TextField(blank=True, db_column='IMDB', null=True)),
                ('summery', models.TextField(blank=True, null=True)),
                ('fid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'film',
                'managed': False,
            },
        ),
    ]
